### ISSUE TITLE
chaduke - The useCollateral() might assign provision.share to each supplier NOT in propotion to the borrow amount from that supplier.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-kairos-judging#110]
chaduke

high

# The useCollateral() might assign provision.share to each supplier NOT in propotion to the borrow amount from that supplier.

## Summary

The useCollateral() might assign provision.share to each supplier NOT in propotion to the borrow amount from that supplier. As a result, a borrower can create an offer for himself, taking a large share of the NFT in future claiming during liquidation.

## Vulnerability Detail
The ``userCollateral()`` function allows a borrower to use a collateral to back a loan, which can borrow tokens from multiple offers.

[https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/BorrowLogic/BorrowHandlers.sol#L100-L126](https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/BorrowLogic/BorrowHandlers.sol#L100-L126)

For each offer and the amount borrowed from each offer, it will calculate the shares of the NFT for that offer as follows:  ``provision.share = borrow amount / arg.offer.loanToValue``, where ``arg.offer.loanToValue`` is the estimated price of the given NFT. 

[https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/BorrowLogic/BorrowHandlers.sol#L28-L93](https://github.com/sherlock-audit/2023-02-kairos/blob/main/kairos-contracts/src/BorrowLogic/BorrowHandlers.sol#L28-L93)

The problem with this calculation is that each offer might give different ``arg.offer.loanToValue``. As a result, in terms of share, it will favor those who give very small ``arg.offer.loanToValue``.

The borrower can actually exploit this vulnerability and steal funds from the protocol and other suppliers: he can create an offer for himself, with a very small ``arg.offer.loanToValue``, and borrow a little from that offer, but will get a big share of the NFT nevertheless, say 95%. Although the borrower borrows most tokens from other offers, the rest of offers might only account for 5%. As a result, he can simply wait for liquidation, and will get 95% of the liquidation proceedings as well as the borrowed tokens. 

## Impact
The useCollateral()  function does not assign shares to lenders in proportion to the borrowed amount from that offers, but this share is greatly affected by the esitmated NFT price by that lender: ``arg.offer.loanToValue``. First of all, this is not fair. Second, the borrower might trick the system and create a fishy offer to steal funds from the system and other lenders during liquidation.

## Code Snippet
See above

## Tool used
VSCode

Manual Review

## Recommendation
We can calculate the total amount borrowed for a loan from all offfers, ``loan.lent``, and use it as the denominator to calculate the share for each lender as:
```javascript
provision.share = borrow amount / loan.lent

```

**Comment by npasquie** [comment]
This design is intentional, please refer to the docs & comments for rationale.
cf https://doc.kairos.loan/in-depth/liquidation.html
cf https://doc.kairos.loan/in-depth/supplying.html ("Kairos guarantees that the lender is at a loss only if it made a mistake by signing an offer with a loanToValue field higher for the corresponding NFT than the fair market price of this NFT at any point in time during the loan lifetime (including auction time")
cf https://github.com/kairos-loan/kairos-contracts/blob/ce49230ab5255662d287c4944229cf411725de3f/src/BorrowLogic/BorrowHandlers.sol#L71-L85
Calculating how much a lender can claim after a liquidation, we have to be fair regarding the risk estimation it made ahead of time. This is why we calculate the share based on its own estimate, it will be at a loss in case of an estimation too high, at a profit otherwise.

**Comment by npasquie** [comment]
similar to #72
